version: '3.8'

services:
  web-calculator:
    build: .
    image: web-calc-production:v1.0
    container_name: glassy-calculator-pro
    ports:
      - "80:8080" # Maps local port 80 to container port 8080
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"